# Data Configuration
data:
  input_path: "data/raw_weekly_hospital_respiratory_data_2020_2024.csv"
  date_column: "Week Ending Date"
  target_column: "Number of Inpatient Beds"
  group_by_column: "Geographic aggregation"
  train_test_split: 0.2
  
  # Feature Engineering Settings
  feature_engineering:
    enabled: true
    time_features:
      enabled: true
      features:
        - "year"
        - "month"
        - "day_of_week"
        - "quarter"
        - "is_weekend"
    lag_features: [1, 7, 30]
    rolling_features:
      windows: [7, 30]
      operations: ["mean", "std", "min", "max"]
    missing_value_handling:
      method: "interpolate"
      interpolation_method: "linear"
      max_gap_to_fill: 7

# Model Configuration
model:
  models_to_try:
    - "random_forest"
    - "xgboost"
  
  random_forest_params:
    n_estimators: 100
    max_depth: 10
    random_state: 42
    
  xgboost_params:
    n_estimators: 100
    max_depth: 7
    learning_rate: 0.1
    random_state: 42

# Output Configuration
output:
  model_path: "models/trained_models.joblib"
  visualization_dir: "visualizations"
  model_comparison_path: "results/model_comparison.csv"

# Visualization Settings
visualizations:
  plot_style: "seaborn-v0_8"
  figure_size: [12, 6]
  save_format: "png" 